# render.yaml
# Defines the services for the quick_linker application on Render.
# This file should be placed at the root of your repository.

services:
  # 1. A managed Redis instance for your application's data store.
  - type: redis
    name: redis-shortener
    plan: free # The 'free' plan is suitable for hobby projects.
    # IP allow list is required. '0.0.0.0/0' allows connections from anywhere.
    ipAllowList:
      - value: 0.0.0.0/0
        description: "Allow all IPs"
    maxmemoryPolicy: allkeys-lru # A good default policy for caching.

  # 2. The Go back-end application, deployed as a Docker container.
  - type: web
    name: quick-linker
    runtime: docker
    plan: free # The 'free' plan is suitable for hobby projects.
    
    # Paths are relative to the repository root.
    dockerContext: ./back-end
    dockerfilePath: ./back-end/dockerfile
    
    envVars:
      # The public URL of this service, provided automatically by Render.
      - key: BASE_URL
        value: $RENDER_EXTERNAL_URL
        
      # The connection string for the Redis service.
      # Your application should be configured to parse this full Redis URL.
      - key: REDIS_ADDR
        fromService:
          type: redis
          name: redis-shortener
          property: connectionString