services:
  app:
    build: .
    container_name: quick_linker
    ports:
      - "8080:8080"
    environment:
      - BASE_URL=http://localhost:8080
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: redis-shortener
    volumes:
      - redis_data:/data

volumes:
  redis_data: